{% set name = "treedecomp" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2895be54f7ea4c2f0ae900c28a500a33a2cdb885e6cb5145692f41fac4953767

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - networkx >=2

test:
  imports:
    - treedecomp

about:
  home: https://gitlab.inria.fr/amibio/treedecomp
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Python Class for Tree Decomposition
  doc_url: https://gitlab.inria.fr/amibio/treedecomp
  dev_url: https://gitlab.inria.fr/amibio/treedecomp

extra:
  recipe-maintainers:
    - anthonyhtyao
