{% set name = "treedecomp" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3228d7a504d5429112ae2afa6d15d1bf3a208fb1f5bc9aa475e874747a3c3a9b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - networkx >=2

test:
  imports:
    - treedecomp

about:
  home: https://gitlab.inria.fr/amibio/treedecomp
  license: GPL-3.0-only
  license_family: GPL3
  license_file: LICENSE.txt
  summary: Python Class for Tree Decomposition
  doc_url: https://gitlab.inria.fr/amibio/treedecomp
  dev_url: https://gitlab.inria.fr/amibio/treedecomp

extra:
  recipe-maintainers:
    - anthonyhtyao
